"""Services layer - Business logic for Odoo operations."""

from odoo_mcp.services import (
    accounting_service,
    calendar_service,
    capability_service,
    chatter_service,
    contract_service,
    crm_service,
    generic_service,
    helpdesk_service,
    hr_service,
    inventory_service,
    invoice_service,
    partner_service,
    project_service,
    purchase_service,
    sales_service,
    view_migration_service,
    workforce_service,
)

__all__ = [
    "calendar_service",
    "accounting_service",
    "capability_service",
    "chatter_service",
    "contract_service",
    "crm_service",
    "generic_service",
    "helpdesk_service",
    "hr_service",
    "inventory_service",
    "invoice_service",
    "partner_service",
    "project_service",
    "purchase_service",
    "sales_service",
    "view_migration_service",
    "workforce_service",
]
